#config port.port=80
#spring-hibernate for mysql
server:
  port: 80

application:
  security:
    jwt:
      secret-key: L6bzNmD7xqJh5P8CzDjZt+vP7uXcQdkVvEdKcM6Zb0kUe3RfTjl3mYvVnF3Wzq6A9Wzhh9mQAfmkUj3eHKtxy7A==
      expiration: 3600000 # thời gian hết hạn token access (ms) - ví dụ: 1 giờ
      refresh-token:
        expiration: 604800000 # thời gian hết hạn refresh token (ms) - ví dụ: 7 ngày



spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  #connection MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/db_local
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

minio:
  endpoint: http://localhost
  port: 9000
  accessKey: admin
  secretKey: admin
  bucketName: my-bucket
  imageSize: 5242880     # 5 MB = 5 * 1024 * 1024
  fileSize: 10485760     # 10 MB = 10 * 1024 * 1024


